language: node_js
sudo: false
node_js:
  - "6.9"
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - yarn install
script:
  - yarn deploy-bizinga
  - yarn deploy-kanga
